name: macOS Release

on:
  push:
    branches:
      - 'trunk'
    tags:
      - 'v*'

env:
  PROG:         cubiomes-viewer
  SOURCE_DIR:   ${{github.workspace}}

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion:   '==3.1.*'
          version:      '5.15.2'
          archives:     'x86_64 qtbase qttools'
          cache:        true
          setup-python: false

      - name: Build
        working-directory: ${{env.SOURCE_DIR}}
        run:  |
              qmake CONFIG+=release ${{env.SOURCE_DIR}}
              CFLAGS="-isysroot /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk" make

      - name: Deploy
        working-directory: ${{env.SOURCE_DIR}}
        run:  |
              macdeployqt ${{env.PROG}}.app -dmg -no-plugins
              ./${{env.PROG}}.app/Contents/MacOS/${{env.PROG}} --version
              otool -L ${{env.PROG}}.app/Contents/MacOS/${{env.PROG}}

      - name: Save build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.PROG}}-${{github.ref_name}}-macos
          path: ${{env.SOURCE_DIR}}/${{env.PROG}}-${{github.ref_name}}.dmg

