name: Source Release

on:
  push:
    branches:
      - 'trunk'
    tags:
      - 'v*'

defaults:
  run:
    shell: bash

env:
  PROG:         cubiomes-viewer
  SOURCE_DIR:   ${{github.workspace}}


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build source bundle
        working-directory: ${{env.SOURCE_DIR}}
        run: |
             rm -rf ./.git*
             cd ..
             tar cvzf ${{env.PROG}}-${{github.ref_name}}-src.tar.gz ${{env.PROG}}
             mv ${{env.PROG}}-${{github.ref_name}}-src.tar.gz ${{env.SOURCE_DIR}}

      - name: Save source artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.PROG}}-${{github.ref_name}}-src.tar.gz
          path: ${{env.PROG}}-${{github.ref_name}}-src.tar.gz


